basic_app/urls.py
from django.conf.urls import url
import basic_app.views as ba

app_name = 'basic_app'

urlpatterns = [
    url(r'^index$',ba.index,name='index'),
    url(r'^formPage',ba.form_name_view,name='form_name_view'),
    url(r'^base',ba.basic,name = 'basic'),
    url(r'other',ba.other,name = 'other'),
]

testsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import url

import hello.views as helloV
import world.views 
# import first_app.views as fa
from django.conf.urls import url,include
from django.contrib import admin
from learning_user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', helloV.somefunction),
    path('getpersons/',helloV.get_all_person),
    # path('world/',world.views.show),
    url("world",include('world.urls')),
    url("First_app",include('first_app.urls')),
    url("basic_app",include('basic_app.urls')),
    url("form_module",include('form_module.urls')),
    url(r'^index$',views.index,name = 'index'),
    url(r'^learning_user/',include('learning_user.urls')),
    url(r'^logout/$',views.user_logout,name = 'logout'),
    url(r'special/',views.special,name = 'special'),
    url(r'^adv_cbv_hello',include('adv_cbv_hello.urls')),
    url(r'clone_project1',include('clone_project1.urls')),
]

world/urls.py
from django.conf.urls import url 
import world.views as wv

urlpatterns = [
    url(r'^world_models$',wv.show ,name = 'show'),
    url(r'^models$',wv.show ,name = 'show'),
]

basic_app/forms.py
from django import forms
from django.core import validators

def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name must be start with z")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label = "Enter your email again:")
    text = forms.CharField(widget = forms.Textarea)
    botcatcher = forms.CharField(required = False,
                                widget = forms.HiddenInput,
                                validators = [validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super(FormName,self).clean()
        email = all_clean_data.get('email')
        verify_email = all_clean_data.get('verify_email')
        if email != verify_email:
            raise forms.ValidationError("Make Sure Emails Match")
        return all_clean_data

        

basic_app/views.py
from django.shortcuts import render
from . import forms 
#or form basic_app import FormName

# Create your views here.
def index(request):
    return render(request,"basic_app/index.html")

def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)
        
        if form.is_valid():
            print("Validation success")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: "+form.cleaned_data['text'])


    return render(request,"basic_app/form_page.html",{'form':form})

def other(request):
    return  render(request,"basic_app/other.html")

def basic(request):
    return render(request,"basic_app/basic.html")

templates/basic_app/basic.html
<!DOCTYPE html>
<html>
    <head>
        <title>Basic</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <h1>Welcome to basic page</h1>
        <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">brand</a>
            </div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'basic_app:basic' %}">admin</a></li>
              <li><a href="{% url 'basic_app:index' %}">index</a></li>
              <li><a href="{% url 'basic_app:other' %}">other</a></li>
            </ul>
          </div>
        </nav>
        <div class="container">
            {% block body_block %}
<!--            anthing outside this inherited if you extend-->
            {% endblock %}
        </div>
    </body>
</html>

templates/basic_app/form_page.html
<!DOCTYPE html>
<html>
    <head>
        <title>Forms</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    </head>
    <body>
        
        <div class = "container">
            <h1>Fill out the form</h1>
            <form method = 'POST'>
                <!-- for line break -->
                {{form.as_p}}
                <!-- for security -->
                {% csrf_token %}
                <input type="submit" class = "btn btn-primary" value="submit">
            </form>
        </div>
    </body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>HOME PAGE</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    </head>
    <body>
        <div class = "container">
            <div class = "jumbotron">
                <h1>Welcome to home page!</h1>
                <h2>Goto /formPage to fill out the form</h2>
            </div>
        </div>
        
    </body>
</html>

templates/basic_app/other.html
<!DOCTYPE html>
    {% extends "basic_app/basic.html" %}
        {% block body_block %}
            <h1>Welcome to other page</h1>
            <h2>This is an example of template inheritance</h2>
        {% endblock %}