first_app/urls.py
from django.conf.urls import url
import first_app.views as fa

app_name = 'first_app'

urlpatterns = [
    url(r'^click',fa.index,name='index'),
    url(r'^other',fa.other,name='other'),
    url(r'^relative',fa.relative,name='relative'),
]

testsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import url

import hello.views as helloV
import world.views 
# import first_app.views as fa
from django.conf.urls import url,include
from django.contrib import admin
from learning_user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', helloV.somefunction),
    path('getpersons/',helloV.get_all_person),
    # path('world/',world.views.show),
    url("world",include('world.urls')),
    url("First_app",include('first_app.urls')),
    url("basic_app",include('basic_app.urls')),
    url("form_module",include('form_module.urls')),
    url(r'^index$',views.index,name = 'index'),
    url(r'^learning_user/',include('learning_user.urls')),
    url(r'^logout/$',views.user_logout,name = 'logout'),
    url(r'special/',views.special,name = 'special'),
    url(r'^adv_cbv_hello',include('adv_cbv_hello.urls')),
    url(r'clone_project1',include('clone_project1.urls')),
]

world/urls.py
from django.conf.urls import url 
import world.views as wv

urlpatterns = [
    url(r'^world_models$',wv.show ,name = 'show'),
    url(r'^models$',wv.show ,name = 'show'),
]

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from hello.models import Person
from django.core import serializers

# Create your views here.
def index(request):
    main_data = {}
    data = Person.objects.all()
    args = {
        'data':data
    }
    return render(request,'first_app/index.html',args)

def other(request):
    return render(request,'first_app/other.html')

def relative(request):
    return render(request,'first_app/relative_url_template.html')

templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>First app</title>
    </head>
    <body>
        <h1>{{insert_me}}</h1>
        <p>{{data}}</p>

        
        <table style="width:auto">
            <tr>
              <th>Firstname</th>
              <th>Lastname</th> 
              <th>Email</th>
            </tr>
            {% for data1 in data %}
            </br>
            <tr>
              <td>{{data1.first_name}}</td>
              <td>{{data1.last_name}}</td> 
              <td>{{data1.email}}</td>
            </tr>
            {% endfor %}
          </table>
          <h2>This is picture of nature</h2>
          <img src="{% static 'images/download.jpeg' %}" alt="image">
          <h1> welcome to index</h1>
    </body>
</html>

templates/first_app/other.html
<!DOCTYPE html>
<html>
    <head>
        <title>Other page</title>
    </head>
    <body>
    <h1>Welcome to other</h1>
    </body>
</html>

templates/first_app/relative_url_template.html
<!DOCTYPE html>
<html>
    <head>
        <title>Relative url</title>
    </head>
    <body>
        <h1>Welcome to relative url template</h1>
        <a href="{% url 'first_app:other' %}">the other page</a>
        <a href="{% url 'first_app:index' %}">index page</a>
    </body>
</html>