adv_cbv_hello/urls.py
from django.conf.urls import url
from adv_cbv_hello import views

app_name = 'adv_cbv_hello'

urlpatterns = [
    # url(r'^$',views.CBview.as_view(),name = "adv_index"),
    # url(r'^index$', views.IndexView.as_view(), name="adv_index2"),
    url(r'^list',views.SchoolListView.as_view(),name = "list"),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name = "detail"),
    url(r'^create/$',views.SchoolCreateView.as_view(),name = "create"),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name = "update"),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name="delete"),
]

learning_user/urls.py
from django.conf.urls import url
from learning_user import views
app_name = 'learning_user'

urlpatterns = [
    url(r'^register/$',views.register,name = 'register'),
    url(r'^user_login',views.user_login,name = "user_login"),
]

testsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import url

import hello.views as helloV
import world.views 
# import first_app.views as fa
from django.conf.urls import url,include
from django.contrib import admin
from learning_user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', helloV.somefunction),
    path('getpersons/',helloV.get_all_person),
    # path('world/',world.views.show),
    url("world",include('world.urls')),
    url("First_app",include('first_app.urls')),
    url("basic_app",include('basic_app.urls')),
    url("form_module",include('form_module.urls')),
    url(r'^index$',views.index,name = 'index'),
    url(r'^learning_user/',include('learning_user.urls')),
    url(r'^logout/$',views.user_logout,name = 'logout'),
    url(r'special/',views.special,name = 'special'),
    url(r'^adv_cbv_hello',include('adv_cbv_hello.urls')),
    url(r'clone_project1',include('clone_project1.urls')),
]

world/urls.py
from django.conf.urls import url 
import world.views as wv

urlpatterns = [
    url(r'^world_models$',wv.show ,name = 'show'),
    url(r'^models$',wv.show ,name = 'show'),
]

adv_cbv_hello/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("adv_cbv_hello:detail",kwargs={'pk':self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE,)

    def __str__(self):
        return self.name

adv_cbv_hello/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.http import HttpResponse
from . import models
# Create your views here.

# def index(request):
#     return render(request,"adv_cbv_hello/index.html")

#for templateview using advance
# class CBview(View):
#     def get(self,request):
#         return HttpResponse("Class based view are cool")
#
# class IndexView(TemplateView):
#     template_name = "adv_cbv_hello/index.html"
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['injectme'] = 'BASIC INJECTION'
#         return context
class IndexView(TemplateView):
    template_name = 'adv_cbv_hello/index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = "adv_cbv_hello/school_detail.html"

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("adv_cbv_hello:list")

adv_cbv_hello/templates/adv_cbv_hello/adv_base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Base</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'adv_cbv_hello:list' %}">Schools</a>
            </div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'admin:index' %}">admin</a></li>
              <li><a href="{% url 'learning_user:register' %}">Register</a></li>
            </ul>
          </div>
        </nav>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

adv_cbv_hello/templates/adv_cbv_hello/school_confirm_delete.html
{% extends "adv_cbv_hello/adv_base.html" %}
{% block body_block %}
    <h1>Delete {{school.name}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class = "btn btn-danger" value="Delete">
        <a href="{% url 'adv_cbv_hello:detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock %}

adv_cbv_hello/templates/adv_cbv_hello/school_detail.html
{% extends "adv_cbv_hello/adv_base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to school detail page</h1>
    <h2>School detail:</h2>
    <p>Name:{{school_detail.name}}</p>
    <p>Principal:{{school_detail.principal}}</p>
    <p>Location:{{school_detail.location}}</p>
    <h3>Students:</h3>
    {% for student in school_detail.students.all %}
        <p>{{student.name}} who is {{student.age}} year old</p>
    {%endfor%}
</div>
<div class="container">
    <p><a class = "btn btn-warning" href="{% url 'adv_cbv_hello:update' pk=school_detail.pk %}">Update</a></p>
</div>
{% endblock %}

adv_cbv_hello/templates/adv_cbv_hello/school_form.html
{% extends "adv_cbv_hello/adv_base.html" %}
{% block body_block %}
    <h1>
        {% if not form.instance.pk %}
            Create School
        {% else %}
            Update School
        {% endif %}
    </h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>
{% endblock %}

adv_cbv_hello/templates/adv_cbv_hello/school_list.html
{% extends "adv_cbv_hello/adv_base.html" %}
{% block body_block %}
<h1>Welcome to list of all school</h1>
<ol>
    {% for school in schools %}
        <h2><li><a href = "adv_cbv_hello{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
</ol>
{% endblock %}