basic_app/urls.py
from django.conf.urls import url
import basic_app.views as ba

app_name = 'basic_app'

urlpatterns = [
    url(r'^index$',ba.index,name='index'),
    url(r'^formPage',ba.form_name_view,name='form_name_view'),
    url(r'^base',ba.basic,name = 'basic'),
    url(r'other',ba.other,name = 'other'),
]

learning_user/urls.py
from django.conf.urls import url
from learning_user import views
app_name = 'learning_user'

urlpatterns = [
    url(r'^register/$',views.register,name = 'register'),
    url(r'^user_login',views.user_login,name = "user_login"),
]

testsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import url

import hello.views as helloV
import world.views 
# import first_app.views as fa
from django.conf.urls import url,include
from django.contrib import admin
from learning_user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', helloV.somefunction),
    path('getpersons/',helloV.get_all_person),
    # path('world/',world.views.show),
    url("world",include('world.urls')),
    url("First_app",include('first_app.urls')),
    url("basic_app",include('basic_app.urls')),
    url("form_module",include('form_module.urls')),
    url(r'^index$',views.index,name = 'index'),
    url(r'^learning_user/',include('learning_user.urls')),
    url(r'^logout/$',views.user_logout,name = 'logout'),
    url(r'special/',views.special,name = 'special'),
    url(r'^adv_cbv_hello',include('adv_cbv_hello.urls')),
    url(r'clone_project1',include('clone_project1.urls')),
]

world/urls.py
from django.conf.urls import url 
import world.views as wv

urlpatterns = [
    url(r'^world_models$',wv.show ,name = 'show'),
    url(r'^models$',wv.show ,name = 'show'),
]

learning_user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,)
    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic',blank = True)

    def __str__(self):
        return self.user.username

learning_user/forms.py
from django import forms
from django.contrib.auth.models import User
from learning_user.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username','email','password']

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ['portfolio_site','profile_pic']

learning_user/views.py
from django.shortcuts import render
from learning_user.forms import UserProfileInfoForm,UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import  authenticate,login,logout
# Create your views here.

def index(request):
    return render(request,'learning_user/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in ,Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'learning_user/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT LOGIN")
        else:
            print("try to login failed")
            print("Username:{} and password:{}".format(username,password))
            return HttpResponse("Invalid login details")
    else:
        return render(request,'learning_user/login.html',{})

templates/learning_user/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Base</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'index' %}">Django</a>
            </div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'basic_app:index' %}">admin</a></li>
              <li><a href="{% url 'learning_user:register' %}">Register</a></li>
                {% if user.is_authenticated %}
                <li><a href = "{% url 'logout'%}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'learning_user:user_login' %}">login</a></li>
                {% endif %}
            </ul>
          </div>
        </nav>
        <div class = "container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

templates/learning_user/index.html
{% extends "learning_user/base.html" %}
{% block body_block %}
    <div class="jumbotron">
       <h1>Django level five</h1>
    </div>
{% endblock %}

templates/learning_user/login.html
{% extends 'learning_user/base.html' %}
{% block body_block %}
    <div class = "jumbotron">
        <h1>Please Login</h1>
        <form action = "{% url 'learning_user:user_login' %}" method = "POST">
            {% csrf_token %}
            <label for = "username">Username:</label>
            <input type = "text" name = "username" placeholder="Enter username">
            <label for = "password">Password:</label>
            <input type = "password" name = "password" placeholder = "Enter Password">
            <input type = "submit" name = "" value = "Login">
        </form>
    </div>
{% endblock %}

templates/learning_user/registration.html
{% extends "learning_user/base.html" %}
{% load static %}
{% block body_block %}
    <div class = "jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register here</h1>
            <h3>Fill out the form:</h3>
            <form enctype = "multipart/form-data" method="Post">
                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <input type = "submit" name = "" value = "Register">
            </form>
        {% endif %}
    </div>
{% endblock %}